flowchart TD
    n0_http___demo_local_a["Static Basic - About<br/>http://demo.local/about.html"]
    n1_http___demo_local_c["Static Basic - Contact<br/>http://demo.local/contact.html"]
    n2_http___demo_local_i["Static Basic - Home<br/>http://demo.local/index.html"]
    n3_http___demo_local_m["Error response<br/>http://demo.local/missing-page.html"]